AppBundle\Entity\BlogPost:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BlogPostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '255'
        body:
            type: text
        draft:
            type: boolean
    lifecycleCallbacks: {  }

    manyToOne:
        category:
            targetEntity: Category
            inversedBy: blogPosts
            joinColumn:
                name: category_id
                referencedColumnName: id
